### ISSUE TITLE
脚本运行以后，貌似崩了

### ISSUE THREAD

**Issue by li5414** [NetEaseGame/AutomatorX#105]
osx系统，ios真机，运行直接报错
<img width="1074" alt="2017-03-06 4 22 31" src="https://cloud.githubusercontent.com/assets/8327631/23601999/4092b788-0289-11e7-8251-913ea7685f21.png">
<img width="502" alt="2017-03-06 4 22 42" src="https://cloud.githubusercontent.com/assets/8327631/23602004/48108cf6-0289-11e7-82e5-1df1c5a6e50b.png">

**Comment by codeskyblue** [comment]
atx 版本都升级到最新，然后重新测试下

**Comment by codeskyblue** [comment]
原因主要是因为wda更新了，所以atx也要跟着更新。最好加qq群，在群里多关注群消息
