### ISSUE TITLE
如何清除输入框里面预置的参数值

### ISSUE THREAD

**Issue by mexth** [NetEaseGame/AutomatorX#106]
举例：使用AutomatorX  测试Mxplayer的时候，有一些选项是有预设值的，每次打开都会保留一个数值，执行clear_text的命令无效：
比如说 
d(text="7", resourceId="android:id/edit", className="android.widget.EditText").clear_text()   执行无效。不会消除掉7这个预设值，
而set_text()的命令则是正常的，
d(resourceId="android:id/edit", className="android.widget.EditText").set_text('10')
但是这样一样数值变成了107， 而不是需要的10.。

而且每次set_text()都会多加几位数字。
咨询下，有好的办法处理这种情况么
![1](https://cloud.githubusercontent.com/assets/18657844/24028506/93ce9ed8-0b0a-11e7-8f37-1ad7e2eca913.JPG)

**Comment by codeskyblue** [comment]
先安装ATX助手

```
python -matx install atx-assistant
```

第一步使用代码选中, 然后清除

```
d(text="7", resourceId="android:id/edit", className="android.widget.EditText").click()
d(text="7", resourceId="android:id/edit", className="android.widget.EditText").clear_text()
```

**Comment by mexth** [comment]
安装过ATX助手，还是不行，最后发现是通过d.clear_text()命令就可以正常清除了。反而是里面加了参数后无法清除。
