### ISSUE TITLE
click android.view.View return false while succeeded indeed

### ISSUE THREAD

**Issue by GLianwei** [NetEaseGame/AutomatorX#124]
## Version information
- ATX Version: 1.1.2.dev18
- Python Version: 2.7.12

## What steps will reproduce the problem?
```
d = atx.connect()
d(className='android.view.View')[1].click()
```
## What is the expected output?
```
View is clicked and return value is True
```

## What do you see instead?
```
View is clicked but return value is False
```

**Comment by codeskyblue** [comment]
这个原因是选中的已经点击过了，处于激活状态，此时再调用点击，就会返回False
