### ISSUE TITLE
iOS系统中的swipe方法有误差

### ISSUE THREAD

**Issue by DoubleHYH** [NetEaseGame/AutomatorX#128]
## Version information
- ATX Version: 1.1.1.dev28
- Python Version: 2.7.11

## What steps will reproduce the problem?
在 iphone 6 plus 上执行

    device = atx.connect("http://localhost:8100")
    device.swipe(361, 340, 361, 144)

滑动的坐标位置不符合预期。如下图，蓝色线为执行后画出来的。而所给的坐标应该是在比较靠右的地方

## Do you have any log or screenshots?

![图1](https://raw.githubusercontent.com/DoubleHYH/ImgRepository/master/1.webp)

![图2](https://raw.githubusercontent.com/DoubleHYH/ImgRepository/master/2.webp)

**Comment by codeskyblue** [comment]
iOS版本？

**Comment by codeskyblue** [comment]
有点需要说明下，ATX是根据实际的像素来确定的坐标系。

```
print d.display
```

你就会发现，屏幕的宽高是WDA-inspector显示的好几倍

**Comment by codeskyblue** [comment]
你这样写可以就对了

```
device = atx.connect("http://localhost:8100")
device.session.swipe(361, 340, 361, 144)
```
