### ISSUE TITLE
AutomatorX 的几个建议

### ISSUE THREAD

**Issue by xudafeng** [NetEaseGame/AutomatorX#71]
- 提供标准化API，降低用户一次性和重复性学习成本，也方便与其他工具链对接，非标准很难扩展
- 用户端和驱动模块解耦，驱动模块尽量复用开源社区已有驱动，避免复制重复问题，释放精力完善用户端体验
- opencv等图片diff是辅助测试手段，属于断言行为，应该与AutomatorX解耦

**Comment by xudafeng** [comment]
@codeskyblue 非常期待与Macaca共建驱动层，或者webdriver服务端

**Comment by lihuazhang** [comment]
opencv等图片diff属于辅助测试手段，属于断言行为，应该与AutomatorX解耦 这块解耦，做成标准通用化UI自动化插件 可能取得的成就超过项目本身。

**Comment by codeskyblue** [comment]
两位大神的意见我看到了，可是怎么拆呢？目前关于图片识别的库已经是分离了的了

**Comment by xudafeng** [comment]
图片识别的库只能python的用户可以用吗？

**Comment by xudafeng** [comment]
@codeskyblue 先改造成基于https://github.com/macacajs/webdriver-server，标准化是第一步

**Comment by codeskyblue** [comment]
只能python用，我先把底层按照webdriver的标准先标准化了吧

**Comment by xudafeng** [comment]
👍

**Comment by codeskyblue** [comment]
@xudafeng 感觉文档就是这个吧 <https://w3c.github.io/webdriver/webdriver-spec.html> 但是怎么感觉这个东西都是为了测试浏览器应用而设计的

**Comment by xudafeng** [comment]
移动端可以扩展标准 https://macacajs.github.io/macaca-wd/

**Comment by codeskyblue** [comment]
@xdf 你给的链接，上面很多都是函数的用法，关于http具体的协议，似乎很少

**Comment by codeskyblue** [comment]
关于API的部分，文档我正在起草中 https://github.com/openatx/webdriver-phone-spec
基本上是写完一个接口，补充一下文档

**Comment by codeskyblue** [comment]
最终还是放弃了 WebDriver协议，这个协议本身是为了Web自动化设计的，对于手机的自动化适应的并不好
