### ISSUE TITLE
常亮功能不支持S7

### ISSUE THREAD

**Issue by zhijing556** [NetEaseGame/AutomatorX#72]
S7港版，型号G930F 8890处理器
系统6.0.1
装了atx助手。
1.常量功能开启后还是会自己息屏。
2.自动调节亮度的功能开启就会导致app停止响应。

**Comment by codeskyblue** [comment]
是不是那个会爆炸的那款

**Comment by zhijing556** [comment]
@_@!  并不是，手雷款叫note7 型号系列是N9300
这个是G930F，港版，三星定制的google系统

**Comment by codeskyblue** [comment]
暂时不修复了，另外这个issue也不属于atx的核心问题
