### ISSUE TITLE
进入一个页面，执行自动化代码d(text=u"中文")，总会先把页面滑倒底

### ISSUE THREAD

**Issue by lyt19871224** [NetEaseGame/AutomatorX#76]
进入一个页面，执行自动化代码d(text=u"中文")，总会先把页面滑倒底

而我手动将页面滑动到初始状态后，就开始查找了，scroll 或者 click就会生效

**Comment by codeskyblue** [comment]
这个代码也不会滑到底呀

**Comment by codeskyblue** [comment]
问题描述的清楚点，可以在重新开issue
