### ISSUE TITLE
ios如何获取某个控件，并对他操作

### ISSUE THREAD

**Issue by lyt19871224** [NetEaseGame/AutomatorX#77]
ios 元素定位方式：wda支持  baseurl   text  classname  xpath

1.baseurl  classname xpath 使用demo能详细的给一个吗？
2.想问下 我如何能获取到页面的某个控件， elements 那个没看懂如何使用

**Comment by codeskyblue** [comment]
WDA启动之后，手机的 IP地址 如果是 10.0.0.1

访问 <http://10.0.0.1:8100/inspector> 就可以查看当前界面的详细信息

**Comment by lyt19871224** [comment]
inspector 获取到的信息有限，比如 只看到了 控件的类型，text，value
根据这些东西无法具体定位一个控件，我想通过控件的name来捕捉到控件 进一步进行操作
而且，有些oc／rn页面 inspector刷不出来，不知道为什么

**Comment by codeskyblue** [comment]
什么样的刷不出来，最好截个图

**Comment by codeskyblue** [comment]
issue太久了，还有这些问题最好可以去 https://github.com/facebook/WebDriverAgent 提，因为iOS的操作部分都是用的Facebook的webdriveragent
