### ISSUE TITLE
安装atx碰到requests冲突，无法完成安装

### ISSUE THREAD

**Issue by jessezyl** [NetEaseGame/AutomatorX#78]
求助两个问题：

1、用“pip install --pre --upgrade atx”安装时，会报“no module named _markerlib”错误，google了一圈，貌似是pip的问题，但没找到很好地解决办法。

2、改用“sudo easy_install atx”，发现会有requests包不同版本冲突问题：

> ......
> Using /usr/local/lib/python2.7/site-packages/atx-1.0.15.dev1-py2.7.egg
> Processing dependencies for atx
> Searching for requests>=2.9.1
> Reading https://pypi.python.org/simple/requests/
> Downloading https://pypi.python.org/packages/2e/ad/e627446492cc374c284e82381215dcd9a0a87c4f6e90e9789afefe6da0ad/requests-2.11.1.tar.gz#md5=ad5f9c47b5c5dfdb28363ad7546b0763
> Best match: requests 2.11.1
> Processing requests-2.11.1.tar.gz
> Writing /tmp/easy_install-u_qubF/requests-2.11.1/setup.cfg
> Running requests-2.11.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-u_qubF/requests-2.11.1/egg-dist-tmp-t1Kfo_
> warning: no files found matching 'test_requests.py'
> creating /usr/local/lib/python2.7/site-packages/requests-2.11.1-py2.7.egg
> Extracting requests-2.11.1-py2.7.egg to /usr/local/lib/python2.7/site-packages
> Adding requests 2.11.1 to easy-install.pth file
> 
> Installed /usr/local/lib/python2.7/site-packages/requests-2.11.1-py2.7.egg
> error: requests 2.11.1 is installed but requests==2.7.0 is required by set(['atx-uiautomator'])
> 

在装atx依赖包时，要求requests>=2.9.1，但最后又报错“requests==2.7.0 is required”，怎么解决冲突? :(

**Comment by codeskyblue** [comment]
http://stackoverflow.com/questions/7446187/no-module-named-pkg-resources

**Comment by jessezyl** [comment]
Done! Thx~
