### ISSUE TITLE
如果获取TextView的内容并保存到字符串变量

### ISSUE THREAD

**Issue by zhaiworld** [NetEaseGame/AutomatorX#80]
## What steps will reproduce the problem?
phone=str(d(resourceId="com.easemob.businesslink:id/tv_telphone").text())
phone=phone[3:]
以上操作主要是想获取TextView中文本内容并保存到字符串中。
以备后面用这些数据来做搜索

## Do you have any log or screenshots?
![image](https://cloud.githubusercontent.com/assets/4532011/19635920/5d727ab8-99f8-11e6-8d00-9070ebb47fd6.png)

之前还尝试过使用
phone=d(resourceId="com.easemob.businesslink:id/tv_telphone").text()
结果也是一样的。

**Comment by codeskyblue** [comment]
可能需要 encode('utf-8') 吧

**Comment by zhaiworld** [comment]
问题解决了，直接这样用就可以了
phone=d(resourceId="com.easemob.businesslink:id/tv_telphone").text
