### ISSUE TITLE
IOS横屏应用click_image坐标错误

### ISSUE THREAD

**Issue by AliNL** [NetEaseGame/AutomatorX#84]
如题，坐标需要转一下。例如iPhone6：(x,y)->(y,750-x)

**Comment by codeskyblue** [comment]
iOS的版本，手机型号？

**Comment by AliNL** [comment]
IOS10.1, iPhone6

**Comment by codeskyblue** [comment]
Are you in China? I don't know the WebDriverAgent is support iOS10 now, it has been a long time issue.

**Comment by AliNL** [comment]
Yes...I'm in China, WebDriverAgent can work by using iproxy

**Comment by AliNL** [comment]
我手动配置了rotation也没有效果，我看click_image里面似乎没有用到rotation的值？（也可能是我看得不够仔细）

**Comment by codeskyblue** [comment]
默认是不需要配置rotation的，因为WDA返回的截图通常来说都是方向应该都是对的。
先确认一下，截图的方向是否正确的。如果歪的话，就需要到 https://github.com/facebook/WebDriverAgent 提issue了

**Comment by AliNL** [comment]
截图的方向是正确的，也能够顺利的找到，只是返回的坐标不对

**Comment by codeskyblue** [comment]
程序返回的坐标原点是在那个位置？可否用个图说明下

**Comment by AliNL** [comment]
![image](https://cloud.githubusercontent.com/assets/16043657/19994026/29d02378-a285-11e6-8d6c-ff8a1af2e8c8.png)

**Comment by AliNL** [comment]
如果image返回坐标没问题的话，就是click的问题了。。。我使用click()的时候，原点确实是左下角的

**Comment by codeskyblue** [comment]
看样子是click的问题，坐标系的转化应该是WDA做的，这个样子应该就是个BUG了。确保升级到最新版的WDA，然后如果问题还有的话，就像 https://github.com/facebook/WebDriverAgent 提交一个issue。通常来说他们会有一天的处理时间间隔

**Comment by AliNL** [comment]
谢谢！
