### ISSUE TITLE
Mac使用atx报错，提示No module named cv2; 'atx' is a package and cannot be directly executed

### ISSUE THREAD

**Issue by Hellengo** [NetEaseGame/AutomatorX#86]
使用 sudo pip install --ignore-installed --pre --upgrade atx  安装，

The directory '/Users/He/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/He/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting atx
  Downloading atx-1.0.15.dev18-py2-none-any.whl (2.4MB)
    100% |████████████████████████████████| 2.4MB 206kB/s
....

    100% |████████████████████████████████| 481kB 213kB/s
Installing collected packages: futures, subprocess32, backports.ssl-match-hostname, six, singledispatch, certifi, backports-abc, tornado, numpy, setuptools, distribute, atx-androguard, requests, facebook-wda, maproxy, PyYAML, atx-uiautomator, aircv, imageio, tqdm, Pillow, atx
  Running setup.py install for subprocess32 ... done
  Running setup.py install for backports.ssl-match-hostname ... done
  Running setup.py install for tornado ... done
  Running setup.py install for distribute ... done
  Running setup.py install for maproxy ... done
  Running setup.py install for PyYAML ... done
Successfully installed Pillow-3.4.2 PyYAML-3.11 aircv-1.4.4 atx-1.0.15.dev18 atx-androguard-3.0 atx-uiautomator-0.2.11.dev3 backports-abc-0.5 backports.ssl-match-hostname-3.5.0.1 certifi-2016.9.26 distribute-0.7.3 facebook-wda-0.0.3.dev6 futures-3.0.5 imageio-1.5 maproxy-0.0.12 numpy-1.12.0b1 requests-2.12.1 setuptools-29.0.1 singledispatch-3.4.0.3 six-1.10.0 subprocess32-3.2.7 tornado-4.3 tqdm-4.5.0

比如执行：python -m atx version
/usr/bin/python: No module named cv2; 'atx' is a package and cannot be directly executed

**Comment by Hellengo** [comment]
![image](https://cloud.githubusercontent.com/assets/7005423/20707298/cd3b57a0-b665-11e6-9080-a4c9ae7758d0.png)

**Comment by Hellengo** [comment]
>>> import atx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/atx/__init__.py", line 21, in <module>
    from atx.drivers import Pattern, Bounds, ImageCrop
  File "/Library/Python/2.7/site-packages/atx/drivers/__init__.py", line 8, in <module>
    from atx import imutils
  File "/Library/Python/2.7/site-packages/atx/imutils.py", line 11, in <module>
    import cv2
ImportError: dlopen(/usr/local/lib/python2.7/site-packages/cv2.so, 2): no suitable image found.  Did find:
	/usr/local/lib/python2.7/site-packages/cv2.so: mach-o, but wrong architecture

**Comment by zhiyuzhao** [comment]
@Hellengo 
这个我也遇到了，在.bashrc配置python环境变量就好了
`export PYTHONPATH="/usr/local/lib/python2.7/site-packages:$PYTHONPATH"`
我的是系统默认python，你看看你的python路径，做替换

**Comment by codeskyblue** [comment]
这个看样子是cv2 安装的问题，重装一下opencv应该就好了

**Comment by AllenVork** [comment]
执行 python -m atx version 出现
D:\software\python\python.exe: No module named six; 'atx' is a package and cannot be directly executed
是什么问题啊，按照 http://timmyreilly.azurewebsites.net/python-pip-virtualenv-installation-on-windows/ 这个步骤装的

**Comment by codeskyblue** [comment]
缺少个six库，装下就好了
