### ISSUE TITLE
Android Api: clear_text 无法全部删除文字

### ISSUE THREAD

**Issue by godzx001** [NetEaseGame/AutomatorX#88]
例如：
edittext里面有abc啊啊啊文字，使用d(resourceId="xxxxxx").clear_text()   
无法全部删除文字，只会删除头部的文字。

手机：小米note  版本6.0.1
atx：1.0.15dev18

**Comment by codeskyblue** [comment]
你用 `d.clear_text()` 试试

**Comment by godzx001** [comment]
d.clear_text()  亲测可行。
