### ISSUE TITLE
AutomatorX有远程操控ios的例子吗？看有个gif动画，AutomatorX是否支持？

### ISSUE THREAD

**Issue by CodeToSurvive1** [NetEaseGame/AutomatorX#89]

**Comment by codeskyblue** [comment]
iOS是支持的，gif动画是最后的结果报告。

**Comment by CodeToSurvive1** [comment]
@codeskyblue 我看动画基本没有延时 动画是经过处理的吗？因为我测试webdriveragent下来发现点击都需要3s，滑动差不多要4s，还是你们的技术实现由单独的处理？

**Comment by codeskyblue** [comment]
点击3s确实有点太慢了，通常来说都是0.5s以内的。并没有做任何特殊的处理，我用的是iPhoneSE

**Comment by CodeToSurvive1** [comment]
@codeskyblue 我尝试了下ipad mini4 iPhone6 iPhone 6s  iPhone6s plus  花费时间都很久，tap像素的时候基本都在两秒开外，滑动效果基本都在三秒开外 而且不同的手机屏幕页面下，相同的操作花费的时间也有差别，感觉像是点击的时候还是找了下本页面的所有的元素，然后根据位置找元素，再对元素进行操作的，不知道是不是这个原因，但是从没遇到1s以内的情况

**Comment by codeskyblue** [comment]
代码贴一下看看，另外更新下xcode，WDA的代码，重新试试
