### ISSUE TITLE
can i use atx to test ios device on windows (same appium)?

### ISSUE THREAD

**Issue by henryhoang92** [NetEaseGame/AutomatorX#91]
I want use atx to test ios device on windows ?

**Comment by codeskyblue** [comment]
yes, you can. WDA export an http address, for example `http://10.0.0.1:8100`

And you can run script on any device

```python
import atx

d = atx.connect("http://10.0.0.1:8100")
````

**Comment by henryhoang92** [comment]
import atx
d = atx.connect("http://192.168.1.27:8100")
retry to connect, error: HTTPConnectionPool(host='192.168.1.27', port=8100): Max retries exceeded with url: /status (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x03438BF0>: Failed to establish a new connection: [Errno 10061] No connection could be made because the target machine actively refused it',))

**Comment by codeskyblue** [comment]
国内的机器吗？

**Comment by henryhoang92** [comment]
How to create a server connect to device real? not local

**Comment by codeskyblue** [comment]
Mac is needed.

**Comment by henryhoang92** [comment]
is it use iMobileDevice connect to device real on windows?

**Comment by codeskyblue** [comment]
no

**Comment by codeskyblue** [comment]
Any way you still need a mac. I can't do anything for it.
