### ISSUE TITLE
可以添加拖拽函数吗？

### ISSUE THREAD

**Issue by eismog** [NetEaseGame/AutomatorX#92]
/usr/local/lib/python2.7/dist-packages/atx/drivers/android.py
  def swipe(self, sx, sy, ex, ey, steps=100):
  """
  Swipe to one postion

  Args:
  sx, sy, ex, ey: int

  Returns:
  None
  """
  return self._uiauto.swipe(sx, sy, ex, ey, steps)

**Comment by codeskyblue** [comment]
提pr

**Comment by codeskyblue** [comment]
too long time
