### ISSUE TITLE
automatorx 输入中文偶尔有乱码 

### ISSUE THREAD

**Issue by wtyvvv** [NetEaseGame/AutomatorX#99]
你好 
python -m atx install atx-assistant
adb shell ime enable com.netease.atx.assistant/.ime.Utf7ImeService
adb shell ime set com.netease.atx.assistant/.ime.Utf7ImeService 这三个步骤是成功的
我用下面代码提输入上去有乱码
u"大家好 空间还是时尚生活是事实是事实 时尚生活事实上事实上身上还是生生世世是说 上海市是事实是事实888事实上身上".encode("utf-7") 

如果我用base64包装一层 直接atx助手不能解析
base64.b64encode(u"hello world中文".encode("utf-7")) 
 他输入的就是base64编码了 不能解析回中文

**Comment by codeskyblue** [comment]
你就直接 d.type( u"你好")  这就可以了

**Comment by codeskyblue** [comment]
为何需要如此复杂

**Comment by wtyvvv** [comment]
直接 d.type( u"你好")  没有任何反应 不能输入任何文字

**Comment by codeskyblue** [comment]
你难道用的模拟器？

**Comment by codeskyblue** [comment]
刚试了下好使呀

**Comment by wtyvvv** [comment]
你好 使用的是真机 估计是版本问题
